connection:
  # Твой локальный IP адрес (интерфейс, с которого пойдет спам)
  source_ip: "0.0.0.0" 
  # Стандартные параметры Minecraft LAN
  multicast_group: "224.0.2.60"
  multicast_port: 4445

settings:
  amount: 5
  interval_ms: 1500
  base_port: 25565

data:
  prefixes:
    - "&7[&bLAN&7]"
  motds:
    - "&eЗаходи скорее!"
  kick_messages:
    - "&cЭтот сервер переполнен!\n&7Попробуйте позже."
    - "&bВы были перенаправлены на основной хаб..."
    - "&6Ошибка авторизации: &fТребуется лицензия."
    - "&dСервер временно недоступен.\n&fТех. работы до 18:00"
