settings:
  amount: 5
  interval_ms: 1500
  base_port: 25565

data:
  prefixes:
    - "&7[&bLAN&7]"
  motds:
    - "&eЗаходи скорее!"
  # Сообщения, которые увидит игрок при попытке входа
  kick_messages:
    - "&cЭтот сервер переполнен!\n&7Попробуйте позже."
    - "&bВы были перенаправлены на основной хаб..."
    - "&6Ошибка авторизации: &fТребуется лицензия."
    - "&dСервер временно недоступен.\n&fТех. работы до 18:00"
