# Настройки спамера
settings:
  amount: 10          # Сколько серверов будет отображаться в списке
  interval_ms: 1500   # Интервал рассылки (MC ищет каждые 1.5 сек)
  base_port: 25565    # Начальный порт (будет увеличиваться для каждого сервера)

# Варианты префиксов и сообщений
data:
  prefixes:
    - "&7[&bPRO&7]"
    - "&e&l[GAMES]"
    - "&f[&c!&f]"
  motds:
    - "&aВыживание с друзьями"
    - "&dБесплатный админ тут"
    - "&6Заходи, мы тебя ждем!"
    - "&bЛокальный сервер #%d"
